#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    platform: h2
#  h2:
#    console:
#      enabled: true
#  batch:
#    initialize-schema: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: password
  batch:
    jdbc:
     initialize-schema: always
    job:
      enabled: false